name: "Detekt Action"
description: "Run Detekt from a centralized location"
inputs:
  github-token:
    description: "Github token used for generating releases"
    required: true
  detekt-config-file:
    description: "Path to custom detekt.yml config file (optional)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Download cURL & update Git
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo apt-get install -y git
      shell: bash
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Detekt Configuration
      run: |
        if [ -n "${{ inputs.detekt-config-file }}" ]; then
          echo 'Using provided custom detekt configuration file'
          cp "${{ inputs.detekt-config-file }}" detekt.yml
        else
          echo 'Downloading centralized configuration'
          curl -L -o detekt.yml https://raw.githubusercontent.com/monta-app/detekt-action/main/conf/detekt.yml
        fi
        ls -a
      shell: bash
    - name: Run Detekt
      uses: alaegin/Detekt-Action@v1.23.7
      with:
        github_token: ${{ inputs.github-token }}
        detekt_config: detekt.yml
