apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Name of the project
  name: detekt-action
  description: Repository for the Kotlin Detekt configuration
  # Specifies the directory of the docs
  annotations:
    backstage.io/techdocs-ref: dir:.
  labels:
    tier: '3'
# The spec defines who becomes the owner of the system in backstage
spec:
  type: tool
  lifecycle: production
  # Name of the squad responsible for the project, e.g. sre or cpi
  owner: sre
  # Name of the greater system, e.g. "solar" is a part of the home system
  system: platform-division
