FROM openjdk:21

WORKDIR /detekt

RUN curl -LO https://github.com/detekt/detekt/releases/download/v1.23.4/detekt-cli-1.23.4-all.jar
RUN curl -LO https://github.com/detekt/detekt/releases/download/v1.23.4/detekt-formatting-1.23.4.jar

COPY conf/detekt.yml detekt.yml
COPY .docker/run_monta_detekt.sh /bin/run_monta_detekt

RUN chmod +x /bin/run_monta_detekt

WORKDIR /app

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["run_monta_detekt"]
